Feat add accessibility testing for storybook
bangits/DS-Architecture pull request #4
Opened 2023-08-28 11:51 UTC by gorsargsyanbangits

2023-08-30 13:18 UTC, ArmenBangits requested changes

2023-08-30 13:18 UTC, ArmenBangits commented on packages/react/src/Button/__tests__/Button.test.tsx
> +    render(<Button onClick={() => {}}>Click me</Button>);
fix eslint error

2023-08-30 13:18 UTC, ArmenBangits commented on apps/react-docs/src/stories/Button.stories.tsx
> +  decorators: [withKnobs, withActions],
move to globall configs

2023-08-31 12:01 UTC, ArmenMesropyan approved these changes

2023-08-31 12:03 UTC, ArmenBangits approved these changes

2023-08-31 12:04 UTC, merged